[[provisioners]]
role = "host_bootstrap"
name = "grafhome-host-bootstrap"
type = "JWK"
default_ttl = "168h"
max_ttl = "720h"
renewal_default_ttl = "168h"
renewal_max_ttl = "720h"
status = "active"

[[provisioners]]
role = "user_enrollment"
name = "grafhome-user-enrollment"
type = "JWK"
default_ttl = "24h"
max_ttl = "unlimited"
renewal_default_ttl = "24h"
renewal_max_ttl = "48h"
status = "active"

[[provisioners]]
role = "proxy_x509"
name = "grafhome-x509-ca-proxy"
type = "ACME"
default_ttl = "720h"
max_ttl = "720h"
status = "active"
