[[user_clients]]
host = "ca-host"
user = "alice"
allow_effectively_infinite_cert = true
status = "active"

[[user_clients]]
host = "proxy-host"
user = "alice"
status = "active"

[[user_clients]]
host = "edge-host"
user = "alice"
status = "active"

[[user_clients]]
host = "laptop-a"
user = "alice"
status = "active"
