//! Render non-secret deployment files from policy and config.
//!
//! Rendering writes into a caller-provided staging directory. It does not write
//! to `/etc`, `/srv`, or any live host path directly; deployment remains a
//! separate operator-controlled phase.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Component, Path, PathBuf};

use serde_json::{Value, json};

use crate::error::{Error, Result};
use crate::model::SiteModel;
use crate::policy::{Endpoint, Host, Provisioner};

/// File generated by the renderer.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct RenderedFile {
    /// Relative path under the staging directory.
    pub path: PathBuf,
    /// Unix file mode intended for install.
    pub mode: u32,
    /// Rendered file contents.
    pub content: String,
}

/// Render all currently modeled deployment files.
pub fn render(model: &SiteModel) -> Result<Vec<RenderedFile>> {
    let mut files = Vec::new();
    let ca_api = required_endpoint(model, "ca_api")?;
    let ca_origin = required_endpoint(model, "ca_origin")?;
    let ca_host = required_host(model, &ca_origin.target)?;
    let proxy_host = required_host(model, &ca_api.target)?;
    let variables = variables(model)?;

    files.push(RenderedFile {
        path: host_path(
            &ca_host.host,
            absolute_child(model.deployment.ca_steppath(), "config/ca.json")?,
        )?,
        mode: 0o640,
        content: render_template(
            include_str!("../templates/step-ca/ca.json.template"),
            &variables,
        )?,
    });
    files.push(RenderedFile {
        path: host_path(&ca_host.host, "etc/systemd/system/step-ca.service")?,
        mode: 0o644,
        content: render_template(
            include_str!("../templates/systemd/step-ca.service.template"),
            &variables,
        )?,
    });
    files.push(RenderedFile {
        path: host_path(
            &proxy_host.host,
            absolute_child(
                &model.deployment.values["GRAFHOME_CA_APACHE_CONF_AVAILABLE"],
                "grafhome-ca-proxy.conf",
            )?,
        )?,
        mode: 0o644,
        content: render_template(
            include_str!("../templates/apache/grafhome-ca.conf.template"),
            &variables,
        )?,
    });

    for host in model
        .policy
        .hosts
        .iter()
        .filter(|host| host.ssh_server == "yes")
    {
        files.push(RenderedFile {
            path: host_path(
                &host.host,
                absolute_child(
                    &model.deployment.values["GRAFHOME_CA_SSH_TRUST_DIR"],
                    "user_ca_keys.pem",
                )?,
            )?,
            mode: 0o644,
            content: String::new(),
        });
        files.push(RenderedFile {
            path: host_path(
                &host.host,
                absolute_child(
                    &model.deployment.values["GRAFHOME_CA_SSH_TRUST_DIR"],
                    "revoked_user_certs",
                )?,
            )?,
            mode: 0o644,
            content: String::new(),
        });
        files.push(RenderedFile {
            path: host_path(&host.host, "etc/ssh/sshd_config.d/grafhome-ca.conf")?,
            mode: 0o644,
            content: render_template(
                include_str!("../templates/sshd_config.d/grafhome-ca.conf.template"),
                &variables,
            )?,
        });
        for principal_file in authorized_principals(model, host)? {
            files.push(principal_file);
        }
    }

    for host in model
        .policy
        .hosts
        .iter()
        .filter(|host| host.ssh_client == "yes")
    {
        files.push(RenderedFile {
            path: host_path(
                &host.host,
                absolute_child(
                    &model.deployment.values["GRAFHOME_CA_SSH_TRUST_DIR"],
                    "ssh_known_hosts",
                )?,
            )?,
            mode: 0o644,
            content: String::new(),
        });
        files.push(RenderedFile {
            path: host_path(&host.host, "etc/ssh/ssh_config.d/grafhome-ca.conf")?,
            mode: 0o644,
            content: render_template(
                include_str!("../templates/ssh_config.d/grafhome-ca.conf.template"),
                &variables,
            )?,
        });
    }

    files.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(files)
}

const TEST_FIXTURE_PATH_PREFIX: &str = "/dev/null/grafhome-ca-test-fixture";

/// Render a JSON fixture with JWK placeholders replaced by public-key provisioners.
///
/// This output is for local validation only. It intentionally rewrites live CA state paths
/// to unusable fixture paths and does not include JWK private material or encrypted
/// provisioner keys. Runtime rollout must still replace placeholders with
/// operator-generated Smallstep provisioner objects.
pub fn materialize_test_ca_fixture_json(model: &SiteModel) -> Result<String> {
    let mut config: Value =
        serde_json::from_str(&rendered_ca_json(model)?).map_err(|source| Error::Json {
            path: PathBuf::from("templates/step-ca/ca.json.template"),
            source,
        })?;
    materialize_test_ca_fixture_state(&mut config)?;
    let provisioners = config
        .pointer_mut("/authority/provisioners")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| Error::Validation {
            field: "templates/step-ca/ca.json.template:authority.provisioners".to_owned(),
            message: "expected provisioners array".to_owned(),
        })?;
    let mut replacements = BTreeMap::new();
    for provisioner in model
        .policy
        .provisioners
        .iter()
        .filter(|entry| entry.status == "active" && entry.r#type == "JWK")
    {
        replacements.insert(
            provisioner_placeholder(&provisioner.name),
            test_jwk_provisioner(provisioner)?,
        );
    }

    for item in provisioners.iter_mut() {
        let Some(placeholder) = item.as_str() else {
            continue;
        };
        if !placeholder.starts_with("RUNTIME_SECRET_PLACEHOLDER:") {
            continue;
        }
        let replacement = replacements
            .remove(placeholder)
            .ok_or_else(|| Error::Validation {
                field: "templates/step-ca/ca.json.template:authority.provisioners".to_owned(),
                message: format!("unknown runtime placeholder {placeholder}"),
            })?;
        *item = replacement;
    }

    if let Some((placeholder, _)) = replacements.into_iter().next() {
        return Err(Error::Validation {
            field: "templates/step-ca/ca.json.template:authority.provisioners".to_owned(),
            message: format!("missing runtime placeholder {placeholder}"),
        });
    }
    serde_json::to_string_pretty(&config).map_err(|source| Error::Json {
        path: PathBuf::from("templates/step-ca/ca.json.template"),
        source,
    })
}

fn materialize_test_ca_fixture_state(config: &mut Value) -> Result<()> {
    let replacements = [
        ("/root", "step/certs/root_ca.crt"),
        ("/crt", "step/certs/intermediate_ca.crt"),
        ("/key", "step/secrets/intermediate_ca_key"),
        ("/db/dataSource", "step/db"),
        ("/db/valueDir", "step/valuedb"),
        ("/ssh/hostKey", "step/secrets/ssh_host_ca_key"),
        ("/ssh/userKey", "step/secrets/ssh_user_ca_key"),
    ];
    for (pointer, suffix) in replacements {
        let Some(value) = config.pointer_mut(pointer) else {
            return Err(Error::Validation {
                field: format!("templates/step-ca/ca.json.template:{pointer}"),
                message: "missing field needed for test fixture materialization".to_owned(),
            });
        };
        *value = json!(format!("{TEST_FIXTURE_PATH_PREFIX}/{suffix}"));
    }
    let Some(address) = config.pointer_mut("/address") else {
        return Err(Error::Validation {
            field: "templates/step-ca/ca.json.template:/address".to_owned(),
            message: "missing field needed for test fixture materialization".to_owned(),
        });
    };
    *address = json!("127.0.0.1:0");
    Ok(())
}

/// Write rendered files under a staging directory.
pub fn write(files: &[RenderedFile], out_dir: impl AsRef<Path>) -> Result<()> {
    let out_dir = out_dir.as_ref();
    prepare_output_root(out_dir)?;
    write_prepared(files, out_dir)
}

/// Write rendered files after first removing stale files from the staging directory.
pub fn write_clean(files: &[RenderedFile], out_dir: impl AsRef<Path>) -> Result<()> {
    let out_dir = out_dir.as_ref();
    if out_dir.exists() {
        ensure_not_symlink(out_dir)?;
        if !out_dir.is_dir() {
            return Err(Error::Validation {
                field: out_dir.display().to_string(),
                message: "render output path must be a directory".to_owned(),
            });
        }
        remove_generated_roots(files, out_dir)?;
    }
    prepare_output_root(out_dir)?;
    write_prepared(files, out_dir)
}

fn write_prepared(files: &[RenderedFile], out_dir: &Path) -> Result<()> {
    for file in files {
        ensure_relative(&file.path)?;
        let target = out_dir.join(&file.path);
        if let Some(parent) = target.parent() {
            create_dir_all_without_symlinks(out_dir, parent)?;
        }
        ensure_not_symlink(&target)?;
        std::fs::write(&target, &file.content).map_err(|source| Error::io(&target, source))?;
        set_mode(&target, file.mode)?;
    }
    Ok(())
}

fn remove_children(dir: &Path) -> Result<()> {
    for entry in std::fs::read_dir(dir).map_err(|source| Error::io(dir, source))? {
        let entry = entry.map_err(|source| Error::io(dir, source))?;
        let path = entry.path();
        remove_existing_path(&path)?;
    }
    Ok(())
}

fn remove_generated_roots(files: &[RenderedFile], out_dir: &Path) -> Result<()> {
    for root in generated_roots(files)? {
        remove_existing_path(&out_dir.join(root))?;
    }
    Ok(())
}

fn generated_roots(files: &[RenderedFile]) -> Result<BTreeSet<PathBuf>> {
    let mut roots = BTreeSet::new();
    for file in files {
        ensure_relative(&file.path)?;
        let mut root = None;
        for component in file.path.components() {
            match component {
                Component::CurDir => {}
                Component::Normal(part) => {
                    root = Some(PathBuf::from(part));
                    break;
                }
                _ => {
                    return Err(Error::Validation {
                        field: file.path.display().to_string(),
                        message: "unsupported staging path component".to_owned(),
                    });
                }
            }
        }
        let root = root.ok_or_else(|| Error::Validation {
            field: file.path.display().to_string(),
            message: "rendered path must name a file under the output directory".to_owned(),
        })?;
        roots.insert(root);
    }
    Ok(roots)
}

fn remove_existing_path(path: &Path) -> Result<()> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(source) => return Err(Error::io(path, source)),
    };
    if metadata.is_dir() && !metadata.file_type().is_symlink() {
        remove_children(path)?;
        std::fs::remove_dir(path).map_err(|source| Error::io(path, source))?;
    } else {
        std::fs::remove_file(path).map_err(|source| Error::io(path, source))?;
    }
    Ok(())
}

fn required_endpoint<'a>(model: &'a SiteModel, role: &str) -> Result<&'a crate::policy::Endpoint> {
    model
        .policy
        .endpoint(role)
        .ok_or_else(|| Error::Validation {
            field: format!("policy/endpoints.tsv:{role}"),
            message: "missing required endpoint".to_owned(),
        })
}

fn required_host<'a>(model: &'a SiteModel, name: &str) -> Result<&'a Host> {
    model.policy.host(name).ok_or_else(|| Error::Validation {
        field: format!("policy/hosts.tsv:{name}"),
        message: "missing required host".to_owned(),
    })
}

fn variables(model: &SiteModel) -> Result<BTreeMap<String, String>> {
    let mut variables = model.deployment.values.clone();
    let ca_api = required_endpoint(model, "ca_api")?;
    let ca_origin = required_endpoint(model, "ca_origin")?;
    variables.insert(
        "GRAFHOME_CA_API_DNS_NAME".to_owned(),
        ca_api.dns_name.clone(),
    );
    variables.insert(
        "GRAFHOME_CA_ORIGIN_DNS_NAME".to_owned(),
        ca_origin.dns_name.clone(),
    );
    variables.insert(
        "GRAFHOME_CA_ORIGIN_PORT".to_owned(),
        ca_origin.port.to_string(),
    );
    variables.insert(
        "GRAFHOME_CA_ORIGIN_ADDRESS".to_owned(),
        ca_origin.address.clone(),
    );
    variables.insert(
        "GRAFHOME_CA_HOST_CERT_PATH".to_owned(),
        format!("{}-cert.pub", variables["GRAFHOME_CA_HOST_KEY_PATH"]),
    );
    variables.insert(
        "GRAFHOME_CA_X509_ALLOWED_DNS_JSON".to_owned(),
        x509_allowed_dns_json(ca_api, ca_origin)?,
    );
    variables.insert(
        "GRAFHOME_CA_PROVISIONERS_JSON".to_owned(),
        provisioners_json(&model.policy.provisioners)?,
    );
    Ok(variables)
}

fn x509_allowed_dns_json(ca_api: &Endpoint, ca_origin: &Endpoint) -> Result<String> {
    let mut names = vec![ca_api.dns_name.as_str(), ca_origin.dns_name.as_str()];
    names.sort_unstable();
    names.dedup();
    serde_json::to_string(&names).map_err(|source| Error::Json {
        path: PathBuf::from("policy/endpoints.tsv"),
        source,
    })
}

fn rendered_ca_json(model: &SiteModel) -> Result<String> {
    render_template(
        include_str!("../templates/step-ca/ca.json.template"),
        &variables(model)?,
    )
}

fn provisioners_json(provisioners: &[Provisioner]) -> Result<String> {
    let mut rendered = Vec::new();
    for provisioner in provisioners.iter().filter(|entry| entry.status == "active") {
        let claims = provisioner_claims(provisioner)?;
        let value = match provisioner.r#type.as_str() {
            "JWK" => json!(provisioner_placeholder(&provisioner.name)),
            "SSHPOP" => json!({
                "type": "SSHPOP",
                "name": provisioner.name,
                "claims": claims
            }),
            "ACME" => json!({
                "type": "ACME",
                "name": provisioner.name,
                "claims": claims
            }),
            other => {
                return Err(Error::Validation {
                    field: format!("policy/provisioners.tsv:{}.type", provisioner.name),
                    message: format!("rendering provisioner type {other} is not implemented"),
                });
            }
        };
        rendered.push(value);
    }
    serde_json::to_string_pretty(&rendered).map_err(|source| Error::Json {
        path: PathBuf::from("policy/provisioners.tsv"),
        source,
    })
}

/// Render the Smallstep claims object for one active provisioner.
///
/// The integration test uses this same policy-to-JSON path when it swaps
/// test-only generated JWK public keys into the rendered config. Keeping that
/// path shared prevents daemon-boot tests from masking drift in provisioner TTLs,
/// while preserving the production invariant that rendered claims come only
/// from active policy rows.
pub fn active_provisioner_claims(model: &SiteModel, name: &str) -> Result<Value> {
    let provisioner = model
        .policy
        .provisioners
        .iter()
        .find(|entry| entry.name == name && entry.status == "active")
        .ok_or_else(|| Error::Validation {
            field: format!("policy/provisioners.tsv:{name}"),
            message: "missing active provisioner".to_owned(),
        })?;
    provisioner_claims(provisioner)
}

fn provisioner_claims(provisioner: &Provisioner) -> Result<Value> {
    let claims = match provisioner.role.as_str() {
        "host_bootstrap" | "host_renew" => json!({
            "defaultHostSSHCertDuration": provisioner.default_ttl,
            "maxHostSSHCertDuration": provisioner.max_ttl,
            "enableSSHCA": true
        }),
        "user_login" => json!({
            "defaultUserSSHCertDuration": provisioner.default_ttl,
            "maxUserSSHCertDuration": provisioner.max_ttl,
            "enableSSHCA": true
        }),
        "proxy_x509" => json!({
            "defaultTLSCertDuration": provisioner.default_ttl,
            "maxTLSCertDuration": provisioner.max_ttl
        }),
        other => {
            return Err(Error::Validation {
                field: format!("policy/provisioners.tsv:{}.role", provisioner.name),
                message: format!("rendering provisioner role {other} is not implemented"),
            });
        }
    };
    Ok(claims)
}

fn test_jwk_provisioner(provisioner: &Provisioner) -> Result<Value> {
    Ok(json!({
        "type": "JWK",
        "name": provisioner.name,
        "key": {
            "use": "sig",
            "kty": "EC",
            "kid": format!("grafhome-ca-test-{}", provisioner.name),
            "crv": "P-256",
            "alg": "ES256",
            "x": "ZBlbApWR0lk8PU1b3AWX4aFCKw-ZjFs-EazBUTNvvtA",
            "y": "hq49jJukEJ5X9Gcu-akYcMlQQoGzK8iwJF_Xou-tA3g"
        },
        "claims": provisioner_claims(provisioner)?
    }))
}

pub(crate) fn provisioner_placeholder(name: &str) -> String {
    format!(
        "RUNTIME_SECRET_PLACEHOLDER:{}",
        provisioner_object_secret_name(name)
    )
}

fn provisioner_object_secret_name(name: &str) -> String {
    let suffix = name
        .bytes()
        .map(|byte| match byte {
            b'a'..=b'z' => (byte as char).to_ascii_uppercase(),
            b'A'..=b'Z' | b'0'..=b'9' => byte as char,
            _ => '_',
        })
        .collect::<String>();
    format!("GRAFHOME_CA_PROVISIONER_{suffix}_JSON")
}

fn authorized_principals(model: &SiteModel, host: &Host) -> Result<Vec<RenderedFile>> {
    let mut by_account = BTreeMap::<String, Vec<String>>::new();
    for access in model
        .policy
        .active_ssh_access()
        .filter(|access| access.host == host.host)
    {
        let user = model
            .policy
            .user(&access.user)
            .ok_or_else(|| Error::Validation {
                field: format!("policy/user-hosts.tsv:{}.user", access.user),
                message: "missing policy user".to_owned(),
            })?;
        by_account
            .entry(access.unix_account.clone())
            .or_default()
            .push(user.principal.clone());
    }

    let mut files = Vec::new();
    for (account, mut principals) in by_account {
        principals.sort();
        principals.dedup();
        files.push(RenderedFile {
            path: host_path(
                &host.host,
                absolute_child(
                    &model.deployment.values["GRAFHOME_CA_AUTH_PRINCIPALS_DIR"],
                    account,
                )?,
            )?,
            mode: 0o644,
            content: format!("{}\n", principals.join("\n")),
        });
    }
    Ok(files)
}

fn render_template(template: &str, variables: &BTreeMap<String, String>) -> Result<String> {
    let mut rendered = template.to_owned();
    for (key, value) in variables {
        rendered = rendered.replace(&format!("${{{key}}}"), value);
    }
    if let Some(start) = rendered.find("${GRAFHOME_CA_") {
        let end = rendered[start..]
            .find('}')
            .map(|offset| start + offset + 1)
            .unwrap_or(rendered.len());
        return Err(Error::Validation {
            field: "render".to_owned(),
            message: format!("unresolved template variable {}", &rendered[start..end]),
        });
    }
    Ok(rendered)
}

fn absolute_child(parent: impl AsRef<str>, child: impl AsRef<str>) -> Result<PathBuf> {
    let parent = Path::new(parent.as_ref());
    if !parent.is_absolute() {
        return Err(Error::Validation {
            field: parent.display().to_string(),
            message: "expected absolute path".to_owned(),
        });
    }
    Ok(parent.join(child.as_ref()))
}

fn host_path(host: &str, path: impl AsRef<Path>) -> Result<PathBuf> {
    let mut relative = PathBuf::from("hosts").join(host);
    let path = path.as_ref();
    if path.is_absolute() {
        for component in path.components() {
            match component {
                Component::RootDir => {}
                Component::Normal(part) => relative.push(part),
                _ => {
                    return Err(Error::Validation {
                        field: path.display().to_string(),
                        message: "unsupported path component".to_owned(),
                    });
                }
            }
        }
    } else {
        relative.push(path);
    }
    ensure_relative(&relative)?;
    Ok(relative)
}

fn ensure_relative(path: &Path) -> Result<()> {
    if path.is_absolute()
        || path
            .components()
            .any(|component| matches!(component, Component::ParentDir))
    {
        Err(Error::Validation {
            field: path.display().to_string(),
            message: "rendered path must be relative and stay under the output directory"
                .to_owned(),
        })
    } else {
        Ok(())
    }
}

fn prepare_output_root(out_dir: &Path) -> Result<()> {
    if out_dir.exists() {
        ensure_not_symlink(out_dir)?;
        if !out_dir.is_dir() {
            return Err(Error::Validation {
                field: out_dir.display().to_string(),
                message: "render output path must be a directory".to_owned(),
            });
        }
    } else {
        std::fs::create_dir_all(out_dir).map_err(|source| Error::io(out_dir, source))?;
    }
    Ok(())
}

fn ensure_no_symlink_components(root: &Path, path: &Path) -> Result<()> {
    let relative = path.strip_prefix(root).map_err(|_| Error::Validation {
        field: path.display().to_string(),
        message: "render path escaped output directory".to_owned(),
    })?;
    let mut current = root.to_path_buf();
    ensure_not_symlink(&current)?;
    for component in relative.components() {
        match component {
            Component::Normal(part) => {
                current.push(part);
                ensure_not_symlink(&current)?;
            }
            Component::CurDir => {}
            _ => {
                return Err(Error::Validation {
                    field: path.display().to_string(),
                    message: "unsupported staging path component".to_owned(),
                });
            }
        }
    }
    Ok(())
}

fn create_dir_all_without_symlinks(root: &Path, path: &Path) -> Result<()> {
    let relative = path.strip_prefix(root).map_err(|_| Error::Validation {
        field: path.display().to_string(),
        message: "render path escaped output directory".to_owned(),
    })?;
    let mut current = root.to_path_buf();
    ensure_not_symlink(&current)?;
    for component in relative.components() {
        match component {
            Component::Normal(part) => {
                current.push(part);
                match std::fs::symlink_metadata(&current) {
                    Ok(metadata) if metadata.file_type().is_symlink() => {
                        return Err(Error::Validation {
                            field: current.display().to_string(),
                            message: "refusing to render through symlinked staging path".to_owned(),
                        });
                    }
                    Ok(metadata) if metadata.is_dir() => {}
                    Ok(_) => {
                        return Err(Error::Validation {
                            field: current.display().to_string(),
                            message: "render staging path component must be a directory".to_owned(),
                        });
                    }
                    Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
                        std::fs::create_dir(&current)
                            .map_err(|source| Error::io(&current, source))?;
                        ensure_not_symlink(&current)?;
                    }
                    Err(source) => return Err(Error::io(&current, source)),
                }
            }
            Component::CurDir => {}
            _ => {
                return Err(Error::Validation {
                    field: path.display().to_string(),
                    message: "unsupported staging path component".to_owned(),
                });
            }
        }
    }
    ensure_no_symlink_components(root, path)
}

fn ensure_not_symlink(path: &Path) -> Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => Err(Error::Validation {
            field: path.display().to_string(),
            message: "refusing to render through symlinked staging path".to_owned(),
        }),
        Ok(_) => Ok(()),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(Error::io(path, source)),
    }
}

#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let permissions = std::fs::Permissions::from_mode(mode);
    std::fs::set_permissions(path, permissions).map_err(|source| Error::io(path, source))
}

#[cfg(not(unix))]
fn set_mode(_path: &Path, _mode: u32) -> Result<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::render;

    #[test]
    fn renders_expected_files_without_live_paths() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let paths = files
            .iter()
            .map(|file| file.path.to_string_lossy().into_owned())
            .collect::<Vec<_>>();

        assert!(paths.contains(&"hosts/ca-host/srv/example-ca/step/config/ca.json".to_owned()));
        assert!(paths.contains(&"hosts/ca-host/etc/systemd/system/step-ca.service".to_owned()));
        assert!(paths.contains(&"hosts/ca-host/etc/ssh/grafhome/user_ca_keys.pem".to_owned()));
        assert!(paths.contains(&"hosts/ca-host/etc/ssh/grafhome/revoked_user_certs".to_owned()));
        assert!(paths.contains(&"hosts/ca-host/etc/ssh/grafhome/ssh_known_hosts".to_owned()));
        assert!(paths.contains(
            &"hosts/proxy-host/etc/apache2/conf-available/grafhome-ca-proxy.conf".to_owned()
        ));
        assert!(paths.contains(&"hosts/ca-host/etc/ssh/auth_principals/alice".to_owned()));
        assert!(paths.iter().all(|path| !path.starts_with('/')));
    }

    #[test]
    fn rendered_apache_proxy_fragment_verifies_https_origin() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let proxy = files
            .iter()
            .find(|file| {
                file.path
                    == std::path::Path::new(
                        "hosts/proxy-host/etc/apache2/conf-available/grafhome-ca-proxy.conf",
                    )
            })
            .unwrap();

        assert!(proxy.content.contains("SSLProxyEngine on"));
        assert!(proxy.content.contains("SSLProxyVerify require"));
        assert!(proxy.content.contains("SSLProxyCheckPeerName on"));
        assert!(
            proxy
                .content
                .contains("SSLProxyCACertificateFile /etc/ssl/example-ca/root_ca.crt")
        );
        assert!(
            proxy
                .content
                .contains("ProxyPass        /.well-known/acme-challenge/ !")
        );
        assert!(
            proxy
                .content
                .contains("ProxyPass        / https://ca-origin.example.test:8443/")
        );
    }

    #[test]
    fn renders_policy_backed_ca_json() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let ca_json = files
            .iter()
            .find(|file| {
                file.path
                    == std::path::Path::new("hosts/ca-host/srv/example-ca/step/config/ca.json")
            })
            .unwrap();

        assert!(ca_json.content.contains("\"dnsNames\""));
        assert!(
            ca_json
                .content
                .contains("\"address\": \"198.51.100.20:8443\"")
        );
        assert!(ca_json.content.contains("\"ca.example.test\""));
        assert!(ca_json.content.contains("\"ca-origin.example.test\""));
        assert!(ca_json.content.contains(
            "\"RUNTIME_SECRET_PLACEHOLDER:GRAFHOME_CA_PROVISIONER_GRAFHOME_USER_LOGIN_JSON\""
        ));
        assert!(ca_json.content.contains("\"type\": \"SSHPOP\""));
        assert!(!ca_json.content.contains("${GRAFHOME_CA_"));
        assert!(!ca_json.content.contains("templateFile"));
    }

    #[test]
    fn rendered_x509_policy_allows_public_and_origin_ca_names() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let ca_json = files
            .iter()
            .find(|file| {
                file.path
                    == std::path::Path::new("hosts/ca-host/srv/example-ca/step/config/ca.json")
            })
            .unwrap();
        let value: serde_json::Value = serde_json::from_str(&ca_json.content).unwrap();

        assert_eq!(
            value["authority"]["policy"]["x509"]["allow"]["dns"],
            serde_json::json!(["ca-origin.example.test", "ca.example.test"])
        );
        assert_eq!(
            value["authority"]["policy"]["x509"]["allowWildcardNames"],
            false
        );
    }

    #[test]
    fn rendered_sshd_fragments_reference_rendered_support_files() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let rendered_paths = files
            .iter()
            .map(|file| file.path.clone())
            .collect::<BTreeSet<_>>();

        for file in files.iter().filter(|file| {
            file.path
                .ends_with("etc/ssh/sshd_config.d/grafhome-ca.conf")
        }) {
            assert!(file.content.contains("PermitRootLogin no"));
            assert!(
                file.content
                    .contains("HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub")
            );
            for path in referenced_sshd_files(&file.content) {
                let host = file.path.components().nth(1).unwrap();
                let relative = super::host_path(&host.as_os_str().to_string_lossy(), path).unwrap();
                assert!(
                    rendered_paths.contains(&relative),
                    "{} references missing rendered support file {}",
                    file.path.display(),
                    relative.display()
                );
            }
        }
    }

    #[test]
    fn rendered_ssh_client_fragments_reference_host_ca_known_hosts() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let rendered_paths = files
            .iter()
            .map(|file| file.path.clone())
            .collect::<BTreeSet<_>>();

        for file in files
            .iter()
            .filter(|file| file.path.ends_with("etc/ssh/ssh_config.d/grafhome-ca.conf"))
        {
            assert!(file.content.contains("/etc/ssh/grafhome/ssh_known_hosts"));
            let host = file.path.components().nth(1).unwrap();
            let relative = super::host_path(
                &host.as_os_str().to_string_lossy(),
                "/etc/ssh/grafhome/ssh_known_hosts",
            )
            .unwrap();
            assert!(
                rendered_paths.contains(&relative),
                "{} references missing rendered support file {}",
                file.path.display(),
                relative.display()
            );
        }
    }

    #[test]
    fn rendered_jwk_provisioners_are_whole_object_placeholders() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let ca_json = files
            .iter()
            .find(|file| {
                file.path
                    == std::path::Path::new("hosts/ca-host/srv/example-ca/step/config/ca.json")
            })
            .unwrap();
        let value: serde_json::Value = serde_json::from_str(&ca_json.content).unwrap();
        let provisioners = value["authority"]["provisioners"].as_array().unwrap();
        let jwk_placeholders = provisioners
            .iter()
            .filter_map(serde_json::Value::as_str)
            .filter(|item| item.starts_with("RUNTIME_SECRET_PLACEHOLDER:"))
            .collect::<Vec<_>>();

        assert_eq!(
            jwk_placeholders,
            vec![
                "RUNTIME_SECRET_PLACEHOLDER:GRAFHOME_CA_PROVISIONER_GRAFHOME_HOST_BOOTSTRAP_JSON",
                "RUNTIME_SECRET_PLACEHOLDER:GRAFHOME_CA_PROVISIONER_GRAFHOME_USER_LOGIN_JSON"
            ]
        );
        assert!(
            provisioners
                .iter()
                .filter(|item| item["type"] == "JWK")
                .count()
                == 0
        );
        assert!(!ca_json.content.contains("ENCRYPTED_KEY"));
    }

    #[test]
    fn materialized_test_ca_fixture_json_replaces_jwk_placeholders() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let ca_json = super::materialize_test_ca_fixture_json(&model).unwrap();
        let value: serde_json::Value = serde_json::from_str(&ca_json).unwrap();
        let provisioners = value["authority"]["provisioners"].as_array().unwrap();
        let host_bootstrap = provisioners
            .iter()
            .find(|item| item["name"] == "grafhome-host-bootstrap")
            .unwrap();
        let user_login = provisioners
            .iter()
            .find(|item| item["name"] == "grafhome-user-login")
            .unwrap();

        assert!(!ca_json.contains("RUNTIME_SECRET_PLACEHOLDER"));
        assert!(!ca_json.contains("/srv/example-ca"));
        assert_eq!(value["address"], "127.0.0.1:0");
        assert_eq!(
            value["root"],
            "/dev/null/grafhome-ca-test-fixture/step/certs/root_ca.crt"
        );
        assert_eq!(
            value["ssh"]["userKey"],
            "/dev/null/grafhome-ca-test-fixture/step/secrets/ssh_user_ca_key"
        );
        assert_eq!(host_bootstrap["type"], "JWK");
        assert_eq!(host_bootstrap["key"]["kty"], "EC");
        assert_eq!(host_bootstrap["key"]["use"], "sig");
        assert!(host_bootstrap.get("encryptedKey").is_none());
        assert!(host_bootstrap["key"].get("d").is_none());
        for provisioner in provisioners {
            assert!(provisioner.get("encryptedKey").is_none());
        }
        assert_eq!(host_bootstrap["claims"]["enableSSHCA"], true);
        assert_eq!(user_login["claims"]["defaultUserSSHCertDuration"], "16h");
        assert_eq!(user_login["claims"]["maxUserSSHCertDuration"], "16h");
    }

    #[test]
    fn rendered_acme_provisioner_does_not_enable_ssh_ca() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let ca_json = files
            .iter()
            .find(|file| {
                file.path
                    == std::path::Path::new("hosts/ca-host/srv/example-ca/step/config/ca.json")
            })
            .unwrap();
        let value: serde_json::Value = serde_json::from_str(&ca_json.content).unwrap();
        let provisioners = value["authority"]["provisioners"].as_array().unwrap();
        let acme = provisioners
            .iter()
            .find(|item| item["name"] == "grafhome-x509-ca-proxy")
            .unwrap();

        assert_eq!(acme["type"], "ACME");
        assert!(acme["claims"].get("enableSSHCA").is_none());
        assert!(acme["claims"].get("defaultUserSSHCertDuration").is_none());
        assert!(acme["claims"].get("defaultHostSSHCertDuration").is_none());
    }

    #[test]
    fn rendered_outputs_do_not_contain_private_key_material() {
        let model = crate::model::SiteModel::load(crate::example_config_root()).unwrap();
        let files = render(&model).unwrap();
        let combined = files
            .iter()
            .map(|file| file.content.as_str())
            .collect::<Vec<_>>()
            .join("\n");

        for label in ["PRIVATE KEY", "OPENSSH PRIVATE KEY"] {
            assert!(!combined.contains(&format!("-----BEGIN {label}-----")));
        }
        assert!(!combined.contains("\"encryptedKey\""));
        assert!(!combined.contains("\"d\""));
    }

    #[cfg(unix)]
    #[test]
    fn write_rejects_symlinked_staging_paths() {
        use std::os::unix::fs::symlink;

        let temp = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let out_dir = temp.path().join("out");
        std::fs::create_dir_all(out_dir.join("hosts/ca-host/etc")).unwrap();
        symlink(outside.path(), out_dir.join("hosts/ca-host/etc/ssh")).unwrap();

        let file = super::RenderedFile {
            path: std::path::PathBuf::from("hosts/ca-host/etc/ssh/auth_principals/alice"),
            mode: 0o644,
            content: "alice\n".to_owned(),
        };
        let error = super::write(&[file], &out_dir).unwrap_err().to_string();

        assert!(error.contains("refusing to render through symlinked staging path"));
        assert!(!outside.path().join("auth_principals").exists());
    }

    #[test]
    fn write_clean_removes_only_generated_roots() {
        let temp = tempfile::tempdir().unwrap();
        let out_dir = temp.path().join("out");
        std::fs::create_dir_all(out_dir.join("hosts/old-host")).unwrap();
        std::fs::write(out_dir.join("hosts/old-host/stale"), "old").unwrap();
        std::fs::write(out_dir.join("operator-notes.txt"), "keep").unwrap();

        let file = super::RenderedFile {
            path: std::path::PathBuf::from("hosts/ca-host/etc/ssh/auth_principals/alice"),
            mode: 0o644,
            content: "alice\n".to_owned(),
        };
        super::write_clean(&[file], &out_dir).unwrap();

        assert!(!out_dir.join("hosts/old-host/stale").exists());
        assert_eq!(
            std::fs::read_to_string(out_dir.join("operator-notes.txt")).unwrap(),
            "keep"
        );
        assert!(
            out_dir
                .join("hosts/ca-host/etc/ssh/auth_principals/alice")
                .exists()
        );
    }

    fn referenced_sshd_files(content: &str) -> Vec<&str> {
        content
            .lines()
            .filter_map(|line| {
                let mut parts = line.split_whitespace();
                let key = parts.next()?;
                if matches!(key, "TrustedUserCAKeys" | "RevokedKeys") {
                    parts.next()
                } else {
                    None
                }
            })
            .collect()
    }
}
